In [137]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [138]:
df = pd.read_csv('train.txt',sep= ";",header = None, names= ['text','emotion'])

In [139]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [140]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [141]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['emotion'] = le.fit_transform(df['emotion'])
df

                                                    text  emotion
0                                i didnt feel humiliated        4
1      i can go from feeling so hopeless to so damned...        4
2       im grabbing a minute to post i feel greedy wrong        0
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        0
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        4
15996  i am now turning and i feel pathetic that i am...        4
15997                     i feel strong and good overall        2
15998  i feel like this was such a rude comment and i...        0
15999  i know a lot but i feel so stupid because i ca...        4

[16000 rows x 2 columns]

In [142]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [143]:
import string

def remove_punch(txt):
    return txt.translate(str.maketrans(' ',' ',string.punctuation))

In [144]:
df['text'] = df['text'].apply(remove_punch)

In [145]:
def remove_digit(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_digit)

In [146]:
df

                                                    text  emotion
0                                i didnt feel humiliated        4
1      i can go from feeling so hopeless to so damned...        4
2       im grabbing a minute to post i feel greedy wrong        0
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        0
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        4
15996  i am now turning and i feel pathetic that i am...        4
15997                     i feel strong and good overall        2
15998  i feel like this was such a rude comment and i...        0
15999  i know a lot but i feel so stupid because i ca...        4

[16000 rows x 2 columns]

In [147]:
import nltk

In [148]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [149]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vivek\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vivek\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vivek\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [150]:
def remove(txt):
    words = word_tokenize(txt)
    return words

df['text'] = df['text'].apply(remove)

In [151]:
df.loc[0]['text']

['i', 'didnt', 'feel', 'humiliated']

In [152]:
stop_words = set(stopwords.words('english'))

def remove_word(txt):
    cleaned = []
    for i in txt:
        if not i in stop_words:
            cleaned.append(i)
    return cleaned

df['text'] = df['text'].apply(remove_word)
df['text'] = df['text'].apply(lambda x : " ".join(x))

In [153]:
df.loc[1]['text']

'go feeling hopeless damned hopeful around someone cares awake'

In [154]:
from sklearn.feature_extraction.text import TfidfTransformer,CountVectorizer

bow_vecterization = CountVectorizer()

In [155]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.2, random_state=42)

In [156]:
X_train_bow = bow_vecterization.fit_transform(X_train)
X_test_bow = bow_vecterization.transform(X_test)

In [157]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

model_nb = MultinomialNB()

In [158]:
model_nb.fit(X_train_bow,y_train)

MultinomialNB()

In [159]:
y_pred = model_nb.predict(X_test_bow)

In [160]:
accuracy_score(y_test,y_pred)

0.7678125