In [75]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [117]:
df = pd.read_csv('train.txt',sep= ";",header = None, names= ['text','emotion'])

In [118]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [119]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [120]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

df['emotion'] = le.fit_transform(df['emotion'])
df

                                                    text  emotion
0                                i didnt feel humiliated        4
1      i can go from feeling so hopeless to so damned...        4
2       im grabbing a minute to post i feel greedy wrong        0
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        0
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        4
15996  i am now turning and i feel pathetic that i am...        4
15997                     i feel strong and good overall        2
15998  i feel like this was such a rude comment and i...        0
15999  i know a lot but i feel so stupid because i ca...        4

[16000 rows x 2 columns]

In [121]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [122]:
import string

def remove_punch(txt):
    return txt.translate(str.maketrans(' ',' ',string.punctuation))

In [123]:
df['text'] = df['text'].apply(remove_punch)

In [124]:
def remove_digit(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_digit)

In [125]:
df

                                                    text  emotion
0                                i didnt feel humiliated        4
1      i can go from feeling so hopeless to so damned...        4
2       im grabbing a minute to post i feel greedy wrong        0
3      i am ever feeling nostalgic about the fireplac...        3
4                                   i am feeling grouchy        0
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        4
15996  i am now turning and i feel pathetic that i am...        4
15997                     i feel strong and good overall        2
15998  i feel like this was such a rude comment and i...        0
15999  i know a lot but i feel so stupid because i ca...        4

[16000 rows x 2 columns]

In [126]:
import nltk

In [127]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [128]:
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\vivek\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\vivek\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\vivek\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [129]:
def remove(txt):
    words = word_tokenize(txt)
    return words

df['text'] = df['text'].apply(remove)

In [131]:
df.loc[0]['text']

['i', 'didnt', 'feel', 'humiliated']

In [135]:
stop_words = set(stopwords.words('english'))

def remove_word(txt):
    cleaned = []
    for i in txt:
        if not i in stop_words:
            cleaned.append(i)
    return cleaned

df['text'] = df['text'].apply(remove_word)

In [140]:
df.loc[1]['text']

['go',
 'feeling',
 'hopeless',
 'damned',
 'hopeful',
 'around',
 'someone',
 'cares',
 'awake']